// Prints the SQL for Better Auth's tables, derived from src/lib/auth.config.ts.
// Usage: node scripts/auth-schema.ts, then diff against migrations/ and write a new
// migration for what changed (0001_auth.sql was its first full output).
import { getMigrations } from "better-auth/db/migration";
import { DatabaseSync } from "node:sqlite";

import { authOptions } from "../src/lib/auth.config.ts";

const { compileMigrations } = await getMigrations(
  authOptions(
    {
      DB: new DatabaseSync(":memory:"),
      BETTER_AUTH_SECRET: "x".repeat(32),
      EMAIL_RATE_LIMIT: { limit: async () => ({ success: true }) },
    },
    () => {},
  ),
);

console.log(`-- Generated by scripts/auth-schema.ts\n${await compileMigrations()}`);
