// Prints the SQL for Better Auth's tables, derived from src/lib/auth.config.ts.
// Usage: node scripts/auth-schema.ts > migrations/0001_auth.sql
import { getMigrations } from "better-auth/db/migration";
import { DatabaseSync } from "node:sqlite";

import { authOptions } from "../src/lib/auth.config.ts";

const { compileMigrations } = await getMigrations(
  authOptions({
    DB: new DatabaseSync(":memory:"),
    BETTER_AUTH_SECRET: "x".repeat(32),
    SIGNUP_CODE: "x",
  }),
);
console.log(`-- Generated by scripts/auth-schema.ts\n${await compileMigrations()}`);
