/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as LandingForgotPasswordRouteImport } from './routes/_landing/forgot-password'
import { Route as LandingLoginRouteImport } from './routes/_landing/login'
import { Route as LandingResetPasswordRouteImport } from './routes/_landing/reset-password'
import { Route as AppRequestsIdRouteImport } from './routes/_app/requests/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const LandingForgotPasswordRoute = LandingForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LandingRoute,
} as any)
const LandingLoginRoute = LandingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LandingRoute,
} as any)
const LandingResetPasswordRoute = LandingResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LandingRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/members': typeof AppMembersRoute
  '/new': typeof AppNewRoute
  '/forgot-password': typeof LandingForgotPasswordRoute
  '/login': typeof LandingLoginRoute
  '/reset-password': typeof LandingResetPasswordRoute
  '/requests/$id': typeof AppRequestsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/members': typeof AppMembersRoute
  '/new': typeof AppNewRoute
  '/forgot-password': typeof LandingForgotPasswordRoute
  '/login': typeof LandingLoginRoute
  '/reset-password': typeof LandingResetPasswordRoute
  '/requests/$id': typeof AppRequestsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/new': typeof AppNewRoute
  '/_landing/forgot-password': typeof LandingForgotPasswordRoute
  '/_landing/login': typeof LandingLoginRoute
  '/_landing/reset-password': typeof LandingResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/requests/$id': typeof AppRequestsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/members'
    | '/new'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/requests/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/members'
    | '/new'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/requests/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/_landing'
    | '/_app/history'
    | '/_app/members'
    | '/_app/new'
    | '/_landing/forgot-password'
    | '/_landing/login'
    | '/_landing/reset-password'
    | '/_app/'
    | '/_app/requests/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_landing/forgot-password': {
      id: '/_landing/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof LandingForgotPasswordRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/login': {
      id: '/_landing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LandingLoginRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/reset-password': {
      id: '/_landing/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LandingResetPasswordRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_app/requests/$id': {
      id: '/_app/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppMembersRoute: typeof AppMembersRoute
  AppNewRoute: typeof AppNewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsIdRoute: typeof AppRequestsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppMembersRoute: AppMembersRoute,
  AppNewRoute: AppNewRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsIdRoute: AppRequestsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LandingRouteChildren {
  LandingForgotPasswordRoute: typeof LandingForgotPasswordRoute
  LandingLoginRoute: typeof LandingLoginRoute
  LandingResetPasswordRoute: typeof LandingResetPasswordRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingForgotPasswordRoute: LandingForgotPasswordRoute,
  LandingLoginRoute: LandingLoginRoute,
  LandingResetPasswordRoute: LandingResetPasswordRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
